[package]
name = "seedpq"
version = "0.1.0"
edition = "2024"

[dependencies]
hybrid-array = "0.3.1"
libc = "0.2.174"
thiserror = "2.0.16"

[dev-dependencies]
criterion = "0.5"
tokio = { version = "1.47.1", features = ["rt", "rt-multi-thread"] }
tokio-postgres = "0.7.13"
wtx = { version = "0.36.1", features = ["postgres", "getrandom"] }
rand_chacha = { features = ["os_rng"], version = "0.9" }

[build-dependencies]
pkg-config = "0.3.32"
bindgen = "0.72.0"

[lib]
crate-type = ["lib"]
bench = false

[[bench]]
name = "channels"
harness = false

[[bench]]
name = "baseline"
harness = false

[[bench]]
name = "wtx"
harness = false
