use std::sync::mpsc::Receiver;

/// Receives notices and warnings sent by postgres.
/// Read: 32.13. Notice Processing
/// Docs: "Notice and warning messages generated by the server are not returned by the query execution functions,
/// since they do not imply failure of the query. Instead they are passed to a notice handling function,
/// and execution continues normally after the handler returns."
/// The methods of this struct will block.
pub struct NoticeReceiver(pub Receiver<String>);
